name: Build iOS App

on:
  [push, workflow_dispatch]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync ios

      - name: init CocoaPods
        run: pod init
        working-directory: ios/App

      - name: Install CocoaPods
        run: pod install --repo-update
        working-directory: ios/App

      - name: Build Xcode project
        run: |
          xcodebuild \
          -workspace App.xcworkspace \
          -scheme App \
          -sdk iphoneos \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY=""
        working-directory: ios/App

      - name: Create Unsigned IPA
        run: |
          mkdir -p Payload
          # Locate the .app file in the derived data folder
          cp -R build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r app.ipa Payload
          rm -rf Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: app.ipa